export interface AnamnesisForm {
  id: number;
  clientId: number;
  fezExtensaoDeCilios: boolean; // "Já fez extensão de cílios?"
  usaLentesDeContato: boolean; // "Usa lente de contato?"
  fazUsoDeOculos: boolean; // "Faz uso de óculos?"
  fezProcedimentoRecenteNosOlhos: boolean; // "Fez algum procedimento recente nos olhos?"
  faraCirurgiaRecentemente: boolean; // "Fará alguma cirurgia recentemente?"
  fazTratamentoHormonal: boolean; // "Faz algum tratamento hormonal?"
  costumaFazerBronzeamento: boolean; // "Costuma fazer bronzeamento?"
  estaGravidaOuTomandoRemediosFertilidadeOuLactante: boolean; // "Está grávida, tomando remédios para fertilidade ou é lactante?"
  possuiAlergiaAoLatexCianoacrilatoOuMicropore: boolean; // "Possui alergia ao látex, cianoacrilato ou micropore?"
  costumaUsarMascaraDeCilios: boolean; // "Costuma usar máscara de cílios?"
  possuiEscleriteBlefariteGlaucomaOuProblemaOcular: boolean; // "Possui esclerite/blefarite/glaucoma ou algum problema ocular?"
  especificarProblemaOcular: string; // "Se sim, especifique"
  desejaFazerTesteAlergico: boolean; // "Deseja fazer o teste alérgico?"
  existeProblemaNecessarioInformar: boolean; // "Existe algum problema que julgue ser necessário informar?"
  autorizaRegistroFotografico: boolean; // "Autoriza o registro fotográfico?"
  jaTeveCovid19: boolean; // "Já teve COVID-19?"
  temFilhos: boolean; // "Tem filhos?"
  quantosFilhos: number; // "Quantos filhos?"
  estaNaMenopausaOuClimaterio: boolean; // "Está na menopausa/climatério?"
  problemasDeSaudeOcular: boolean; // "Problemas de saúde ocular?"
  especificarProblemasDeSaudeOcular: string; // "Se sim, especifique"
  problemasDeSaude: boolean; // "Problemas de saúde?"
  usaProdutosComAcidosNoRosto: boolean; // "Usa produtos à base de ácidos no rosto?"
  estaComSintomasDeCovid19: boolean; // "Está com algum sintoma de COVID-19?"
  eTabagista: boolean; // "É tabagista?"
  ingereBebidasAlcoolicas: boolean; // "Ingere bebidas alcoólicas?"
  dormeDeQualLado: string; // "Dorme de qual lado?"
  estaFazendoDieta: boolean; // "Está fazendo dieta?"
  usaMaquiagemFrequentemente: boolean; // "Usa maquiagem frequentemente?"
  praticaNatacao: boolean; // "Pratica natação?"
  praticaSauna: boolean; // "Pratica sauna?"
  praticaAtividadeFisica: boolean; // "Pratica atividade física?"
  alergiaCosmeticos: boolean; // "Tem alergia a cosméticos?"
  alergiaFitaAdesiva: boolean; // "Tem alergia a fita adesiva?"
  alergiaMaquiagem: boolean; // "Tem alergia a maquiagem?"
  alergiaEsmaltes: boolean; // "Tem alergia a esmaltes?"
}
  